# Generated by Django 3.2.8 on 2022-08-06 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('Country_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EORTechniques',
            fields=[
                ('EOR_Techniques_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('EOR_Type', models.CharField(max_length=100)),
                ('EOR_Type_Description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('Formation_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Formation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lithology',
            fields=[
                ('Lithology_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Lithology', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EORsubType',
            fields=[
                ('EOR_SubType_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('EOR_Sub_Type', models.CharField(max_length=100)),
                ('EOR_Sub_Type_Description', models.CharField(max_length=1000)),
                ('EOR_Type', models.ForeignKey(db_column='EOR_Type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='casestudies.eortechniques')),
            ],
        ),
        migrations.CreateModel(
            name='CaseStusies',
            fields=[
                ('CaseStusies_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Field', models.CharField(max_length=50)),
                ('Pool_Name', models.CharField(max_length=50)),
                ('Flood_Type', models.CharField(choices=[('Vertical', 'Vertical'), ('Horizontal', 'Horizontal'), ('Combination', 'Combination')], max_length=15)),
                ('Number_of_Wells', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('Number_of_EOR_Injectors', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('Number_of_EOR_Producers', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('Discovery_Date', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('EOR_start_year', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('Secondary_Recovery', models.CharField(choices=[('Vertical', 'Vertical'), ('Horizontal', 'Horizontal'), ('Combination', 'Combination')], max_length=50)),
                ('EOR_1', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('EOR_2', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('EOR_3', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('EOR_4', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('Depth_m', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('Average_Pay_Thickness_m', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('Average_Permeability_md', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('Average_Porosity', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('Water_Saturation', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('Initial_Pressure_kPa', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('Initial_Temperature_C', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('Oil_Gravity_API', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('Oil_Density_kgm3', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('Oil_Viscosity_15C_cp', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('Oil_Viscosity_Tr_cp', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('Salinity_of_Formation_Water_ppm', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('Presence_of_Natural_Fractures', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15, null=True)),
                ('Presence_of_Gas_Cap', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True)),
                ('Area_of_Project_ha', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('Primary_Recovery_Factor_fraction', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('Incremental_WF_Recovery_Factor_fraction', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('Incremental_EOR_Recovery_Factor_fraction', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('Total_Recovery_Factor_fraction', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('OOIP_E3m3', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('Remaining_Oil_in_Place_E3m3_after_Primary_EOR_Recovery', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('Remaining_Recoverable_Reserves_E3m3', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('EOR_Sub_Type', models.ForeignKey(db_column='EOR_Sub_Type', on_delete=django.db.models.deletion.DO_NOTHING, to='casestudies.eorsubtype')),
                ('EOR_Type', models.ForeignKey(db_column='EOR_Type', on_delete=django.db.models.deletion.DO_NOTHING, to='casestudies.eortechniques')),
                ('Formation', models.ForeignKey(db_column='Formation', on_delete=django.db.models.deletion.DO_NOTHING, to='casestudies.formation')),
                ('Lithology', models.ForeignKey(db_column='Lithology', on_delete=django.db.models.deletion.DO_NOTHING, to='casestudies.lithology')),
                ('country', models.ForeignKey(db_column='Country', on_delete=django.db.models.deletion.DO_NOTHING, to='casestudies.country')),
            ],
        ),
    ]
