# Generated by Django 3.2.8 on 2022-08-07 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestusies',
            name='Formation',
            field=models.CharField(max_length=50),
        ),
    ]
