# Generated by Django 3.2.8 on 2022-08-07 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0002_alter_casestusies_formation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Formation',
        ),
    ]
