# Generated by Django 3.2.8 on 2022-08-07 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0003_delete_formation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestusies',
            name='Secondary_Recovery',
            field=models.CharField(max_length=50),
        ),
    ]
