# Generated by Django 3.2.8 on 2022-08-07 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0004_alter_casestusies_secondary_recovery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestusies',
            name='EOR_1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='EOR_2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='EOR_3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='EOR_4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='Secondary_Recovery',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
