# Generated by Django 3.2.8 on 2022-08-07 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0005_auto_20220807_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestusies',
            name='Area_of_Project_ha',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='Average_Pay_Thickness_m',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='Average_Permeability_md',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='Average_Porosity',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='Discovery_Date',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='EOR_start_year',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='Incremental_EOR_Recovery_Factor_fraction',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='Incremental_WF_Recovery_Factor_fraction',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='Initial_Pressure_kPa',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='Initial_Temperature_C',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='Number_of_EOR_Injectors',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='Number_of_EOR_Producers',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='Number_of_Wells',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='OOIP_E3m3',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='Oil_Density_kgm3',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='Oil_Gravity_API',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='Oil_Viscosity_15C_cp',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='Oil_Viscosity_Tr_cp',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='Primary_Recovery_Factor_fraction',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='Remaining_Oil_in_Place_E3m3_after_Primary_EOR_Recovery',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='Remaining_Recoverable_Reserves_E3m3',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='Salinity_of_Formation_Water_ppm',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='Total_Recovery_Factor_fraction',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='Water_Saturation',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
    ]
