# Generated by Django 3.2.8 on 2022-08-07 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0006_auto_20220807_0235'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
