# Generated by Django 3.2.8 on 2022-08-11 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0007_mymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestusies',
            name='summary',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='Area_of_Project_ha',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='Average_Porosity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='Discovery_Date',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='EOR_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='EOR_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='EOR_3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='EOR_4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='EOR_start_year',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='Formation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='Incremental_EOR_Recovery_Factor_fraction',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='Incremental_WF_Recovery_Factor_fraction',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='Initial_Pressure_kPa',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='Initial_Temperature_C',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='Lithology',
            field=models.ForeignKey(blank=True, db_column='Lithology', on_delete=django.db.models.deletion.DO_NOTHING, to='casestudies.lithology'),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='Number_of_EOR_Injectors',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='Number_of_EOR_Producers',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='OOIP_E3m3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='Oil_Density_kgm3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='Oil_Gravity_API',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='Oil_Viscosity_15C_cp',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='Oil_Viscosity_Tr_cp',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='Pool_Name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='Presence_of_Gas_Cap',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='Presence_of_Natural_Fractures',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='Primary_Recovery_Factor_fraction',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='Remaining_Oil_in_Place_E3m3_after_Primary_EOR_Recovery',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='Remaining_Recoverable_Reserves_E3m3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='Salinity_of_Formation_Water_ppm',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='Secondary_Recovery',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='Total_Recovery_Factor_fraction',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='Water_Saturation',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
