# Generated by Django 3.2.8 on 2022-08-11 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0008_auto_20220811_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestusies',
            name='Average_Pay_Thickness_m',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='Average_Permeability_md',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='Depth_m',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='casestusies',
            name='Number_of_Wells',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
