# Generated by Django 3.2.8 on 2022-08-11 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0009_auto_20220811_0136'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CaseStusies',
            new_name='CaseStudies',
        ),
        migrations.RenameField(
            model_name='casestudies',
            old_name='CaseStusies_id',
            new_name='CaseStudies_id',
        ),
    ]
