# Generated by Django 3.2.8 on 2022-08-11 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0010_auto_20220811_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudies',
            name='EOR_Sub_Type',
            field=models.ForeignKey(db_column='EOR_Sub_Type', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Sub_Type', to='casestudies.eorsubtype'),
        ),
        migrations.AlterField(
            model_name='casestudies',
            name='EOR_Type',
            field=models.ForeignKey(db_column='EOR_Type', on_delete=django.db.models.deletion.DO_NOTHING, related_name='EORType', to='casestudies.eorsubtype'),
        ),
        migrations.AlterField(
            model_name='eorsubtype',
            name='EOR_Type',
            field=models.ForeignKey(db_column='EOR_Type', on_delete=django.db.models.deletion.DO_NOTHING, to='casestudies.eortechniques'),
        ),
        migrations.AlterField(
            model_name='eortechniques',
            name='EOR_Type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
