# Generated by Django 3.2.8 on 2022-08-11 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0013_remove_casestudies_eor_sub_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudies',
            name='image1',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
