# Generated by Django 3.2.8 on 2022-08-11 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0014_casestudies_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudies',
            name='image1',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
