# Generated by Django 3.2.8 on 2022-08-11 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0019_alter_image_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudies',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='casestudies',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='casestudies',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='casestudies',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='casestudies',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='casestudies',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
