# Generated by Django 3.2.8 on 2022-08-12 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0020_auto_20220811_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudies',
            name='EOR_Sub_Type',
            field=models.CharField(blank=True, choices=[], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='casestudies',
            name='EOR_Type',
            field=models.ForeignKey(db_column='EOR_Type', on_delete=django.db.models.deletion.DO_NOTHING, related_name='EORType', to='casestudies.eortechniques'),
        ),
    ]
