# Generated by Django 3.2.8 on 2022-08-12 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0021_auto_20220812_0341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casestudies',
            name='EOR_Sub_Type',
        ),
        migrations.AlterField(
            model_name='casestudies',
            name='EOR_Type',
            field=models.ForeignKey(db_column='EOR_Type', on_delete=django.db.models.deletion.DO_NOTHING, related_name='EORType', to='casestudies.eorsubtype'),
        ),
    ]
