# Generated by Django 3.2.8 on 2022-08-12 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0022_auto_20220812_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudies',
            name='EOR_Type',
            field=models.ForeignKey(blank=True, db_column='EOR_Type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='EORType', to='casestudies.eorsubtype'),
        ),
        migrations.AlterField(
            model_name='casestudies',
            name='Formation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='casestudies',
            name='country',
            field=models.ForeignKey(blank=True, db_column='Country', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='casestudies.country'),
        ),
    ]
