# Generated by Django 3.2.8 on 2022-08-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0026_alter_casestudies_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudies',
            name='summary',
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
