# Generated by Django 3.2.8 on 2022-08-13 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0033_auto_20220813_0611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casestudies',
            old_name='caseStudies_id',
            new_name='casestudies_id',
        ),
    ]
