# Generated by Django 3.2.8 on 2022-08-13 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0036_joincasestudies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joincasestudies',
            old_name='joincasestudies_id',
            new_name='casestudies_id',
        ),
    ]
