# Generated by Django 3.2.8 on 2022-08-14 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0038_auto_20220813_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casestudies',
            name='country',
        ),
        migrations.AddField(
            model_name='casestudies',
            name='country_id',
            field=models.ForeignKey(blank=True, db_column='country_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='casestudies.country'),
        ),
    ]
