# Generated by Django 3.2.8 on 2022-08-15 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0039_auto_20220814_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casestudies',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='casestudies',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='casestudies',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='casestudies',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='casestudies',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='casestudies',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='joincasestudies',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='joincasestudies',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='joincasestudies',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='joincasestudies',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='joincasestudies',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='joincasestudies',
            name='image6',
        ),
    ]
